scenario_id = 2
num_simulations = 50
comm_range = 200
num_vehicles = 300
vehicle_interval = 6
shelter_capacity_threshold = 1.0
driver_visibility_distance = 50
following_rate = 0.2
active_route_change_mean = 180.0
active_route_change_var = 15.0
positive_lanechange_start = 900
positive_lanechange_end = 1100
active_shelter_occupancy_rate_threshold_start = 0.65
active_shelter_occupancy_rate_threshold_end = 0.8
cautious_route_change_mean = 240.0
cautious_route_change_var = 15.0
negative_lanechange_start = 800
negative_lanechange_end = 1100
cautious_shelter_occupancy_rate_threshold_start = 0.8
cautious_shelter_occupancy_rate_threshold_end = 0.95
tsunami_sign_start_time = 1200
tsunami_sign_end_time = 1500
motivation_threshold_start = 800
motivation_threshold_end = 1000
min_motivation_start = 500
min_motivation_end = 700
positive_majority_bias = 100.0
negative_majority_bias = 100.0
shelter_A_capacity = 150
vehicles_to_shelter_A = 150
shelter_B_capacity = 150
vehicles_to_shelter_B = 150
active_normalcy_value_about_vehicle_abandonment_mean = 2000
active_normalcy_value_about_vehicle_abandonment_var  = 800
active_majority_value_about_vehicle_abandonment_mean = 2500
active_majority_value_about_vehicle_abandonment_var  = 500
active_vehicle_abandoned_threshold_mean = 3000
active_vehicle_abandoned_threshold_var  = 5000
cautious_normalcy_value_about_vehicle_abandonment_mean = 4000
cautious_normalcy_value_about_vehicle_abandonment_var  = 800
cautious_majority_value_about_vehicle_abandonment_mean = 2500
cautious_majority_value_about_vehicle_abandonment_var  = 500
cautious_vehicle_abandoned_threshold_mean = 6000
cautious_vehicle_abandoned_threshold_var  = 7000