scenario_id = 53
num_simulations = 50
comm_range = 200
num_vehicles = 400
vehicle_interval = 5
choice_shortest_route_rate = 0.9
p_follow = 0.4
active_route_change_threshold_center = 300.0
active_route_change_threshold_spread = 100.0
cautious_route_change_threshold_center = 5200.0
cautious_route_change_threshold_spread = 840.0
normalcy_value_about_route_change_center = 600.0
normalcy_value_about_route_change_spread = 120.0
active_vehicle_abandantment_threshold_center = 5000.0
active_vehicle_abandantment_threshold_spread = 400.0
cautious_vehicle_abandantment_threshold_center = 5500.0
cautious_vehicle_abandantment_threshold_spread = 450.0
active_wrong_way_driving_threshold_center = 5500.0
active_wrong_way_driving_threshold_spread = 400.0
cautious_wrong_way_driving_threshold_center = 6000.0
cautious_wrong_way_driving_threshold_spread = 450.0
min_motivation_start = 2500
min_motivation_end = 3200
active_normalcy_value_about_tsunami_precursor_info_center = 650.0
active_normalcy_value_about_tsunami_precursor_info_spread = 150.0
cautious_normalcy_value_about_tsunami_precursor_info_center = 350.0
cautious_normalcy_value_about_tsunami_precursor_info_spread = 100.0
active_normalcy_value_about_route_congestion_info_center = 600.0
active_normalcy_value_about_route_congestion_info_spread = 130.0
cautious_normalcy_value_about_route_congestion_info_center = 300.0
cautious_normalcy_value_about_route_congestion_info_spread = 90.0
active_normalcy_value_about_shelter_full_info_center = 650.0
active_normalcy_value_about_shelter_full_info_spread = 150.0
cautious_normalcy_value_about_shelter_full_info_center = 350.0
cautious_normalcy_value_about_shelter_full_info_spread = 100.0
active_majority_increase_value_center = 400.0
active_majority_increase_value_spread = 150.0
cautious_majority_increase_value_center = 400.0
cautious_majority_increase_value_spread = 150.0
active_majority_decrease_value_center = 300.0
active_majority_decrease_value_spread = 120.0
cautious_majority_decrease_value_center = 300.0
cautious_majority_decrease_value_spread = 120.0
active_shelter_occupancy_rate_threshold_start = 0.65
active_shelter_occupancy_rate_threshold_end = 0.8
cautious_shelter_occupancy_rate_threshold_start = 0.8
cautious_shelter_occupancy_rate_threshold_end = 0.95
shelter_capacity_threshold = 1.0
tsunami_sign_start_time = 600
tsunami_sign_end_time = 800
driver_visibility_distance = 50
alpha = 0.1
following_rate = 0.2
shelter_A_capacity = 150
vehicles_to_shelter_A = 150
shelter_B_capacity = 150
vehicles_to_shelter_B = 15
