scenario_id = 8
num_simulations = 50
comm_range = 200
num_vehicles = 200
vehicle_interval = 5
shelter_capacity_threshold = 1.0
driver_visibility_distance = 50
following_rate = 0.2
active_route_change_mean = 300.0
active_route_change_var = 60.0
positive_lanechange_start = 900
positive_lanechange_end = 1100
active_shelter_occupancy_rate_threshold_start = 0.65
active_shelter_occupancy_rate_threshold_end = 0.8
cautious_route_change_mean = 4200.0
cautious_route_change_var = 60.0
negative_lanechange_start = 800
negative_lanechange_end = 1100
cautious_shelter_occupancy_rate_threshold_start = 0.8
cautious_shelter_occupancy_rate_threshold_end = 0.95
tsunami_sign_start_time = 600
tsunami_sign_end_time = 800
motivation_threshold_start = 800
motivation_threshold_end = 1000
min_motivation_start = 500
min_motivation_end = 700
positive_majority_bias = 100.0
negative_majority_bias = 100.0
shelter_A_capacity = 150
vehicles_to_shelter_A = 150
shelter_B_capacity = 150
vehicles_to_shelter_B = 150
active_normalcy_value_about_vehicle_abandonment_mean = 4000
active_normalcy_value_about_vehicle_abandonment_var  = 800
active_majority_value_about_vehicle_abandonment_mean = 2000
active_majority_value_about_vehicle_abandonment_var  = 500
active_vehicle_abandoned_threshold_mean = 16000
active_vehicle_abandoned_threshold_var  = 19000
cautious_normalcy_value_about_vehicle_abandonment_mean = 6000
cautious_normalcy_value_about_vehicle_abandonment_var  = 800
cautious_majority_value_about_vehicle_abandonment_mean = 2000
cautious_majority_value_about_vehicle_abandonment_var  = 500
cautious_vehicle_abandoned_threshold_mean = 33000
cautious_vehicle_abandoned_threshold_var  = 40000
alpha = 0.5